//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp44.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class materail_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materail_import()
        {
            this.Product_material = new HashSet<Product_material>();
        }
    
        public int id_mater { get; set; }
        public string name { get; set; }
        public Nullable<int> id_type_mater { get; set; }
        public Nullable<int> price_mater { get; set; }
        public Nullable<int> kolich { get; set; }
        public Nullable<int> min_kolich { get; set; }
        public Nullable<int> kolich_yp { get; set; }
    
        public virtual ed_iz ed_iz { get; set; }
        public virtual Material_type Material_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_material> Product_material { get; set; }
    }
}
