//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp44.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oboiShopEntities : DbContext
    {
        public oboiShopEntities()
            : base("name=oboiShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ed_iz> ed_iz { get; set; }
        public virtual DbSet<ed_izmer_chir> ed_izmer_chir { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<materail_import> materail_import { get; set; }
        public virtual DbSet<Material_type> Material_type { get; set; }
        public virtual DbSet<Pathners> Pathners { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<Product_material> Product_material { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
