//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp44.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_material
    {
        public int id { get; set; }
        public Nullable<int> id_Product { get; set; }
        public Nullable<int> id_Material { get; set; }
        public Nullable<int> kolich_mater { get; set; }
    
        public virtual materail_import materail_import { get; set; }
        public virtual product product { get; set; }
    }
}
