//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp44.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Pathners = new HashSet<Pathners>();
            this.Product_material = new HashSet<Product_material>();
        }
    
        public int id_product { get; set; }
        public Nullable<int> id_type_product { get; set; }
        public string name { get; set; }
        public Nullable<int> articul { get; set; }
        public Nullable<int> price_partner { get; set; }
        public Nullable<int> id_chir { get; set; }
    
        public virtual ed_izmer_chir ed_izmer_chir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pathners> Pathners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_material> Product_material { get; set; }
        public virtual product_type product_type { get; set; }
    }
}
